apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fastestpath-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fastestpath
    spec:
      containers:
      - name: fastestpath-container
        image: us.gcr.io/fastestpath-148019/fastestpath-image:5dcdd9f17d92424f401b48acb29b41e09ce3d174
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /tmp/data
          name: fastestpath-mount
      volumes:
        - name: fastestpath-mount
          persistentVolumeClaim:
            claimName: fastestpath-volume-claim
