kind: PersistentVolume
apiVersion: v1
metadata:
  name: fastestpath-volume
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data"