kind: PersistentVolume
apiVersion: v1
metadata:
  name: fastestpath-volume
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    # This disk must already exist.
    # gcloud compute disks create --size 50GB fastestpath-disk
    pdName: fastestpath-disk
    fsType: ext4
