environment: production
server:
  type: simple
  rootPath: /*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9000
logging:
  level: INFO
resourceDirectory: "/tmp/data"
firebase:
  keyPath: "keys/firebase.json"
  databaseUrl: "https://fastestpath-148019.firebaseio.com/"
fetchIntervalHours: 6
