environment: production
server:
  type: simple
  rootPath: /*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9000
logging:
  level: INFO
resourceDirectory: "/tmp/data"
fetchIntervalHours: 6
