environment: production
server:
  type: simple
  rootPath: /*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9000
logging:
  level: INFO
resourceDirectory: /tmp/data/gtfs-archive
fetchIntervalHours: 6
archiveUrl: "http://data.trilliumtransit.com/gtfs/path-nj-us/path-nj-us.zip"
