environment: production
server:
  type: simple
  rootPath: /*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9000
logging:
  level: INFO
gtfs:
  fetchIntervalHours: 6
  saveLocation: src/scheduler/resources/gtfs-archive
  url: "http://data.trilliumtransit.com/gtfs/path-nj-us/path-nj-us.zip"
