environment: production
server:
  type: simple
  rootPath: /*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9000
logging:
  level: DEBUG
resourceDirectory: "/tmp/data"
