environment: production
server:
  type: simple
  rootPath: /*
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9000
logging:
  level: INFO
resourceDirectory: /tmp/data/gtfs-archive
firebase:
  keyPath: firebase.json
  databaseUrl: "https://fastestpath-148019.firebaseio.com/"
  uid: local
fetchIntervalHours: 6
